env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - '@typhonjs-fvtt/eslint-config-foundry.js'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    // Override rules here
    'max-len': ['error', { 'code': 120 }], // Increase max line length to 120
  }
